#!/usr/bin/env bash

cd $(cd "$(dirname "$0")/.." && pwd)

rm -rf $(pwd)/.venv && \
python3 -m venv .venv && \
. .venv/bin/activate && \
python -m pip install --upgrade pip && \
pip install -r requirements.txt
